Description: >
    Victor Cazacov
    This template deploys a VPC with EKS cluster

Parameters:
  # Paramenters are entirely optional.
  # but using them will make your cloudformation templates more reusable
  # use them for things that may change over time, such as instance type,
  # VPCs and so on.

  EKSIAMRoleName:
    Type: String
    Default: "Udacity_EKS_Role"

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Udacity-DevOps-Capstone



Resources:
    EKSIAMRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - eks.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        RoleName: !Ref EKSIAMRoleName
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
          - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

Outputs:
  EKSIAMRoleArn:
    Description: EKS IAM Role
    Value: !GetAtt EKSIAMRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKSIAMRoleArn